spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_local?zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false

server:
  port: 2000
  servlet:
    context-path: /wms